// ============================================================
// Calisthenics 12S — DONNÉES DU PROGRAMME (verbatim de l'app originale)
// Ne pas perdre : échauffements, exercices, conseils, alternatives, tests.
// ============================================================
const PH=[
  {id:1,name:"Phase 1",long:"Adaptation & Technique",weeks:[1,2,3,4],color:"#1A7A4A",bg:"#D6F0E2",grad:"linear-gradient(135deg,#0F5C34,#1A7A4A)"},
  {id:2,name:"Phase 2",long:"Progression & Volume",weeks:[5,6,7,8],color:"#1E5FA8",bg:"#D6E4F7",grad:"linear-gradient(135deg,#143F72,#1E5FA8)"},
  {id:3,name:"Phase 3",long:"Consolidation & Force",weeks:[9,10,11,12],color:"#C05000",bg:"#FDE8D8",grad:"linear-gradient(135deg,#8B3700,#C05000)"},
];
const WG={
  1:"Apprendre les mouvements. Aucune douleur articulaire.",
  2:"Introduire la corde à sauter. Évaluer les genoux.",
  3:"+2 reps sur la plupart des exercices.",
  4:"TEST DE FIN DE PHASE 1 — Faire les tests mesurables.",
  5:"Variantes plus difficiles. Augmenter la résistance des élastiques.",
  6:"+1 série sur les exercices principaux.",
  7:"Réduire les temps de repos de 10-15 sec.",
  8:"TEST DE FIN DE PHASE 2 — Faire les tests mesurables.",
  9:"Variantes avancées. Tenter la première traction négative.",
  10:"Diamond push-up cible : 10 reps propres.",
  11:"Séances les plus intenses du programme.",
  12:"TEST FINAL — Bilan complet. Fêter les progrès ! 🎉",
};
const SESS={
  "p1-lu":{title:"Lundi · Full Body A",sub:"Force & Technique",dur:"35-40 min",rpe:"5/10",goal:"Poser les bases technique + introduction des exercices cibles",
    wu:["Marche sur place 1 min","Rotations d'épaules 10x chaque sens","Rotations de hanches 10x","Cercles de poignets 10x","Fentes statiques basses 30 sec/côté","Cat-Cow 8 rép lentes","Squats partiels lents x10"],
    ex:[
      {n:"Squat partiel (¾ amplitude)",s:3,r:"12 rép",rest:60,tip:"Dos droit, genoux dans l'axe des pieds. Stop avant la douleur.",alt:"Hip hinge debout si douleur genou"},
      {n:"Pompes inclinées (mains sur chaise)",s:3,r:"10 rép",rest:60,tip:"Corps gainé. Pas d'effondrement des hanches.",alt:"Pompes sur genoux"},
      {n:"No-bar back row (élastique)",s:3,r:"10 rép",rest:60,tip:"Coudes serrés, omoplates en arrière. Pas de balancement.",alt:"Rowing assis élastique"},
      {n:"Gainage planche (genoux)",s:3,r:"15 sec",rest:45,tip:"Hanches pas trop hautes. Respirer normalement.",alt:"Superman allongé"},
      {n:"Superman",s:2,r:"10 rép",rest:45,tip:"Soulever bras et jambes, tenir 2 sec en haut.",alt:"Pont fessier"},
      {n:"Leg raises (genoux fléchis)",s:2,r:"8 rép",rest:45,tip:"Dos collé au sol. Descente lente contrôlée.",alt:"Dead bug lent"},
    ],
    cd:["Pectoraux contre mur 30 sec","Fléchisseurs hanche en fente basse 30 sec/côté","Ischios assis 30 sec","Child's pose 45 sec","Rotation thoracique allongé 30 sec/côté"]},
  "p1-me":{title:"Mercredi · Full Body B",sub:"Force + Core",dur:"35-40 min",rpe:"5/10",goal:"Progresser sur les push-ups, introduire diamond push-up et V-taps",
    wu:["Marche sur place 1 min","Rotations d'épaules 10x","Rotations de hanches 10x","Cercles de poignets 10x","Cat-Cow 8 rép","Pont fessier 10 rép","Squats partiels x10"],
    ex:[
      {n:"Squat partiel",s:3,r:"12 rép",rest:60,tip:"Même technique que lundi. On affine.",alt:"Pont fessier"},
      {n:"Pompes classiques",s:3,r:"8-10 rép",rest:60,tip:"Si fatigue : finir sur genoux. Qualité > quantité.",alt:"Pompes sur genoux"},
      {n:"Diamond push-up incliné (chaise)",s:2,r:"6 rép",rest:75,tip:"Mains en diamant sur chaise. Triceps++.",alt:"Pompes inclinées normales"},
      {n:"No-bar back row (bande forte)",s:3,r:"10 rép",rest:60,tip:"Tension constante pendant tout le mouvement.",alt:"Rowing assis"},
      {n:"V-taps (debout ou assis)",s:3,r:"10 rép",rest:45,tip:"En V renversé, toucher les pieds. Core actif.",alt:"Leg raises genoux fléchis"},
      {n:"Gainage planche (pieds)",s:3,r:"20 sec",rest:45,tip:"Ventre rentré, fessiers serrés. Progression vs lundi.",alt:"Planche sur genoux"},
    ],
    cd:["Pigeon pose 40 sec/côté","Mollets au mur 30 sec/côté","Quadriceps debout 30 sec/côté","Child's pose 45 sec","Respiration abdominale 1 min"]},
  "p1-ve":{title:"Vendredi · Full Body C",sub:"Cardio léger + Volume",dur:"40-45 min",rpe:"5/10",goal:"Introduire le cardio faible impact, augmenter légèrement le volume",
    wu:["Marche rapide sur place 2 min","Rotations complètes des bras 10x","Hip circles 10x chaque sens","Fentes dynamiques 6x/côté","Cat-Cow 8 rép","Band pull-apart élastique 15 rép"],
    ex:[
      {n:"Marche active (départ)",s:1,r:"10 min",rest:0,tip:"Rythme soutenu, bras qui bougent. Pas de course.",alt:"Marche lente sur place 5 min"},
      {n:"Squat partiel",s:3,r:"15 rép",rest:60,tip:"Volume légèrement augmenté vs lundi.",alt:"Hip hinge debout"},
      {n:"Pompes inclinées",s:3,r:"12 rép",rest:60,tip:"On cherche la fluidité, pas la vitesse.",alt:"Pompes sur genoux"},
      {n:"No-bar back row",s:3,r:"12 rép",rest:60,tip:"Contrôle à la montée ET à la descente.",alt:"Rowing assis élastique"},
      {n:"Leg compression (genoux levés assis)",s:3,r:"10 sec tenir",rest:45,tip:"Progression vers le L-sit. Dos droit, abdos activés.",alt:"Dead bug lent"},
      {n:"Superman",s:2,r:"12 rép",rest:45,tip:"+2 rép vs semaine 1.",alt:"Pont fessier"},
    ],
    cd:["Thread the needle 30 sec/côté","Ischios assis 45 sec","Fente basse fléchisseurs hanche 40 sec/côté","Rotation lombaire allongé 30 sec/côté","Child's pose 60 sec"]},
  "p2-lu":{title:"Lundi · Force + Volume",sub:"Full Body A · Phase 2",dur:"40-45 min",rpe:"6/10",goal:"Augmenter le volume total et introduire des variantes plus difficiles",
    wu:["Step jacks 1 min","Rotations d'épaules complètes 10x","Hip circles debout 10x","Fentes dynamiques 6x/côté","Squat to stand 8 rép","Inchworm 5 rép","Band pull-apart élastique 15 rép"],
    ex:[
      {n:"Squat complet (amplitude progressive)",s:4,r:"12 rép",rest:60,tip:"Si genoux OK, descendre progressivement plus bas. Jamais sous la douleur.",alt:"Squat partiel x15 ou step-ups"},
      {n:"Pompes classiques",s:4,r:"12-15 rép",rest:60,tip:"Si >15 sans effort : passer aux pompes déclinées.",alt:"Pompes sur genoux"},
      {n:"Diamond push-up (au sol)",s:3,r:"8 rép",rest:75,tip:"Version au sol maintenant. Progression depuis incliné.",alt:"Diamond incliné chaise"},
      {n:"No-bar back row (élastique plus fort)",s:4,r:"12 rép",rest:60,tip:"Augmente la résistance de l'élastique.",alt:"Rowing assis tension maximale"},
      {n:"Gainage planche (pieds)",s:4,r:"30 sec",rest:45,tip:"+10 sec vs phase 1.",alt:"Planche sur genoux 45 sec"},
      {n:"Leg compression (durée augmentée)",s:3,r:"15 sec tenir",rest:45,tip:"Cherche à avoir les jambes plus hautes. Vers le L-sit.",alt:"Leg raises genoux fléchis"},
      {n:"V-taps",s:3,r:"12 rép",rest:45,tip:"Contrôle du mouvement, pas de balancement.",alt:"Leg raises normaux"},
    ],
    cd:["Pigeon pose 45 sec/côté","Mollets au mur 30 sec/côté","Quadriceps debout 30 sec/côté","Thread the needle 30 sec/côté","Child's pose étendu 45 sec","Respiration abdominale 1 min"]},
  "p2-me":{title:"Mercredi · Cardio + Force",sub:"Full Body B · Phase 2",dur:"40-45 min",rpe:"6-7/10",goal:"Intégrer le cardio dans la séance, monter l'intensité globale",
    wu:["Step jacks 1 min","Rotations d'épaules 10x","Hip circles 10x","Inchworm avec pompe 5 rép","Squat to stand 8 rép","Band pull-apart 15 rép"],
    ex:[
      {n:"Corde à sauter (ou step jacks)",s:3,r:"45 sec + 30 sec repos",rest:60,tip:"Sauts légers sur avant-pied. Pause dès gêne genou.",alt:"Step jacks ou shadowboxing 45 sec"},
      {n:"Pompes classiques",s:4,r:"15 rép",rest:60,tip:"Rythme soutenu mais contrôlé. Descente 2 sec.",alt:"Pompes sur genoux x20"},
      {n:"No-bar back row supination",s:4,r:"12 rép",rest:60,tip:"Paumes vers le haut. Biceps travaillent plus.",alt:"Row standard"},
      {n:"Squat + montée sur pointes",s:3,r:"10 rép",rest:75,tip:"Pas de saut si douleur genou. Juste le talon qui se lève.",alt:"Pont fessier pulsé x15"},
      {n:"Superman pulsé",s:3,r:"12 rép",rest:45,tip:"Petites impulsions en haut au lieu de tenir.",alt:"Superman classique"},
      {n:"Gainage latéral",s:3,r:"25 sec/côté",rest:45,tip:"Corps en ligne droite. Hanches qui ne tombent pas.",alt:"Gainage frontal"},
    ],
    cd:["Pigeon pose 45 sec/côté","Mollets au mur 30 sec/côté","Ischios assis 45 sec","Rotation lombaire allongé 30 sec/côté","Child's pose 60 sec"]},
  "p2-ve":{title:"Vendredi · Circuit + Endurance",sub:"Full Body C · Phase 2",dur:"40-45 min",rpe:"7/10",goal:"Endurance musculaire + cardio soutenu. On tient plus longtemps.",
    wu:["Marche rapide ou step jacks 2 min","Fentes avec rotation thoracique 6x/côté","Inchworm 5 rép","Band pull-apart 15 rép","Squat to stand 8 rép"],
    ex:[
      {n:"Marche active",s:1,r:"15 min",rest:0,tip:"Maintenir un rythme où parler est difficile.",alt:"Step-ups lents sur marche"},
      {n:"Circuit : squat + pompe + V-tap",s:4,r:"30 sec effort / 30 sec repos",rest:60,tip:"Enchaîner les 3 sans pause. Modifier si douleur.",alt:"Réduire à 20 sec effort / 40 sec repos"},
      {n:"Diamond push-up",s:4,r:"8-10 rép",rest:75,tip:"Progression +2 rép vs semaine 5.",alt:"Diamond incliné chaise"},
      {n:"No-bar back row (excentrique 3 sec)",s:4,r:"12 rép",rest:60,tip:"Contrôle parfait. Descente ultra-lente.",alt:"Row standard"},
      {n:"Leg compression (L-sit initiation)",s:3,r:"20 sec tenir",rest:45,tip:"Les jambes commencent à s'étendre devant.",alt:"Leg compression genoux fléchis"},
      {n:"Corde à sauter cool-down",s:1,r:"3 min continu",rest:0,tip:"Rythme très léger. Récupération active.",alt:"Marche active 3 min"},
    ],
    cd:["Étirements complets 10 min","Pigeon pose, mollets, ischios, quadriceps","Child's pose 60 sec","Respiration profonde 2 min"]},
  "p3-lu":{title:"Lundi · Force Maximale",sub:"Full Body A · Phase 3",dur:"40-45 min",rpe:"7/10",goal:"Variantes avancées, force maximale, explosivité",
    wu:["Corde à sauter 2 min (modéré) ou step jacks","Fentes avec rotation thoracique 6x/côté","Inchworm avec pompe 5 rép","Band pull-apart + overhead 10x","Squat to stand 8 rép","Dead hang barre 15 sec"],
    ex:[
      {n:"Squat complet avec pause en bas 2 sec",s:4,r:"12 rép",rest:60,tip:"Contrôle total. La pause en bas augmente la difficulté.",alt:"Squat sans pause x15 ou step-ups"},
      {n:"Pompes explosives",s:3,r:"8 rép",rest:90,tip:"Explosion vers le haut. Alternative : pompes rapides.",alt:"Pompes rapides x12"},
      {n:"Pompes classiques",s:3,r:"15-20 rép",rest:60,tip:"Volume. Finir sur genoux si épuisé.",alt:"Pompes sur genoux"},
      {n:"Diamond push-up",s:4,r:"10-12 rép",rest:75,tip:"On progresse vers 12 reps propres.",alt:"Diamond incliné"},
      {n:"No-bar back row (excentrique 3 sec)",s:4,r:"12 rép",rest:60,tip:"Très efficace pour le dos et les biceps.",alt:"Row standard"},
      {n:"Gainage planche",s:4,r:"45 sec",rest:45,tip:"On vise 1 min en fin de phase 3.",alt:"Planche sur genoux 60 sec"},
      {n:"L-sit progression (jambes semi-tendues)",s:3,r:"15 sec tenir",rest:60,tip:"Genoux à 90°, puis progressivement jambes plus droites.",alt:"Leg compression 20 sec"},
    ],
    cd:["Pigeon pose 45 sec/côté","Ischios assis 45 sec","Rotation lombaire allongé 30 sec/côté","Thread the needle 30 sec/côté","Child's pose 60 sec"]},
  "p3-me":{title:"Mercredi · Cardio Intensif + Force",sub:"Full Body B · Phase 3",dur:"40-45 min",rpe:"7/10",goal:"Cardio poussé, V push-up, préparation traction",
    wu:["Corde à sauter 2 min ou step jacks","Fentes dynamiques 8x/côté","Inchworm 5 rép","Band pull-apart 15 rép","Hip flexor stretch 8x/côté","Dead hang barre 15 sec"],
    ex:[
      {n:"Corde à sauter",s:4,r:"1 min saut / 30 sec repos",rest:60,tip:"Rythme modéré constant. On tient la minute complète.",alt:"Step jacks ou shadowboxing 1 min"},
      {n:"V push-up (corps en V inversé)",s:3,r:"6-8 rép",rest:90,tip:"Descendre la tête vers le sol. Épaules++.",alt:"Pompes déclinées (pieds surélevés)"},
      {n:"No-bar back row supination",s:4,r:"15 rép",rest:60,tip:"Biceps + dos. Contrôle parfait.",alt:"Row standard"},
      {n:"Squat jump (contrôlé)",s:4,r:"10 rép",rest:75,tip:"Atterrissage souple sur avant-pied.",alt:"Step-ups rapides sur chaise"},
      {n:"V-taps avancés",s:3,r:"15 rép",rest:45,tip:"Plus rapide ou amplitude augmentée.",alt:"V-taps normaux"},
      {n:"Dead hang à la barre",s:3,r:"20-30 sec",rest:90,tip:"Activation omoplates en bas. Vers la traction.",alt:"Band pull-apart debout 20 rép"},
    ],
    cd:["Étirements complets 10-15 min","Pigeon pose, mollets, ischios","Thread the needle","Child's pose 60 sec"]},
  "p3-ve":{title:"Vendredi · Circuit Final",sub:"Full Body C · Phase 3 — Le plus intense",dur:"45 min",rpe:"8/10",goal:"Séance la plus complète du programme. Test d'endurance.",
    wu:["Corde à sauter 3 min ou step jacks","Inchworm avec pompe 5 rép","Squat to stand 10 rép","Band pull-apart 15 rép","Dead hang barre 15 sec"],
    ex:[
      {n:"Marche active",s:1,r:"20 min",rest:0,tip:"Base maintenant. Rythme plus rapide qu'en phase 1.",alt:"Step-ups lents"},
      {n:"Circuit : pompe + V-tap + squat + row élastique",s:5,r:"40 sec effort / 20 sec repos",rest:90,tip:"Séance la plus intense. Rythme élevé.",alt:"30 sec effort / 30 sec repos"},
      {n:"Traction négative",s:3,r:"3-5 rép (5 sec descente)",rest:120,tip:"Monte sur tabouret, tiens la barre, descends lentement.",alt:"Dead hang actif 3x20 sec"},
      {n:"Diamond push-up",s:4,r:"12 rép",rest:75,tip:"Objectif final : 12 rép propres, coudes serrés.",alt:"Diamond incliné"},
      {n:"L-sit (jambes tendues)",s:3,r:"10 sec tenir",rest:60,tip:"Objectif final du programme.",alt:"L-sit genoux à 90° 20 sec"},
      {n:"Corde à sauter (cool-down)",s:1,r:"5 min continu",rest:0,tip:"Rythme régulier. Récupération active.",alt:"Marche active 5 min"},
    ],
    cd:["Étirements complets 15 min","Tout le corps : hanches, ischios, mollets, épaules, dos","Respiration profonde 2 min"]},
};
const TESTS=[
  {w:0,lbl:"Test Initial",exs:[
    {n:"Pompes classiques",u:"rép",base:30},{n:"Squats (amplitude max)",u:"rép",base:45},
    {n:"Gainage planche",u:"sec",base:20},{n:"Dead hang barre",u:"sec",base:20},
    {n:"Traction négative (5 sec)",u:"rép",base:0},{n:"Corde à sauter continue",u:"min",base:0},
    {n:"Diamond push-up (sol)",u:"rép",base:0},{n:"L-sit / Leg compression",u:"sec",base:10},
  ]},
  {w:4,lbl:"Test Semaine 4",exs:[
    {n:"Pompes classiques",u:"rép",tgt:35},{n:"Squats (amplitude max)",u:"rép",tgt:45},
    {n:"Gainage planche",u:"sec",tgt:35},{n:"Dead hang barre",u:"sec",tgt:30},
    {n:"Traction négative (5 sec)",u:"rép",tgt:1},{n:"Corde à sauter continue",u:"min",tgt:3},
    {n:"Diamond push-up (sol)",u:"rép",tgt:5},{n:"L-sit / Leg compression",u:"sec",tgt:15},
  ]},
  {w:8,lbl:"Test Semaine 8",exs:[
    {n:"Pompes classiques",u:"rép",tgt:45},{n:"Squats (amplitude max)",u:"rép",tgt:60},
    {n:"Gainage planche",u:"sec",tgt:50},{n:"Dead hang barre",u:"sec",tgt:40},
    {n:"Traction négative (5 sec)",u:"rép",tgt:3},{n:"Corde à sauter continue",u:"min",tgt:8},
    {n:"Diamond push-up (sol)",u:"rép",tgt:8},{n:"L-sit / Leg compression",u:"sec",tgt:15},
  ]},
  {w:12,lbl:"Test Final S.12",exs:[
    {n:"Pompes classiques",u:"rép",tgt:50},{n:"Squats (amplitude max)",u:"rép",tgt:80},
    {n:"Gainage planche",u:"sec",tgt:60},{n:"Dead hang barre",u:"sec",tgt:50},
    {n:"Traction négative (5 sec)",u:"rép",tgt:5},{n:"Corde à sauter continue",u:"min",tgt:15},
    {n:"Diamond push-up (sol)",u:"rép",tgt:12},{n:"L-sit / Leg compression",u:"sec",tgt:10},
  ]},
];
const CHK=[
  {id:"lu",lbl:"Séance Lundi",ic:"💪"},{id:"me",lbl:"Séance Mercredi",ic:"💪"},
  {id:"ve",lbl:"Séance Vendredi",ic:"💪"},{id:"marche",lbl:"Marche ≥ 3 fois",ic:"🚶"},
  {id:"corde",lbl:"Corde à sauter",ic:"⚡"},{id:"mob",lbl:"Mobilité / étirements",ic:"🧘"},
  {id:"som",lbl:"Sommeil correct (≥7h)",ic:"😴"},{id:"eau",lbl:"Hydratation (≥2,5L)",ic:"💧"},
  {id:"dok",lbl:"Aucune douleur articulaire",ic:"✅"},
];
function sesKeys(w){ return w<=4?["p1-lu","p1-me","p1-ve"]:w<=8?["p2-lu","p2-me","p2-ve"]:["p3-lu","p3-me","p3-ve"]; }
function phase(w){ return w<=4?PH[0]:w<=8?PH[1]:PH[2]; }
